host_from:
  host: rabbitmq
  port: 5432
  user: guest
  password: guest

host_to:
  host: rabbitmq
  port: 5432
  user: guest
  password: guest

queues:
  - queue-response-1
  - queue-response-1-error
  - queue-requests-2
  - queue-response-3
